services:
  nestjs-api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src

  pg_db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: MksPass123
      POSTGRES_USER: mksUser
      POSTGRES_DB: mks_movies_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 