services:
  nestjs-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - pg_db
      - redis

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  pg_db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: MksPass123
      POSTGRES_USER: mksUser
      POSTGRES_DB: mks_movies_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - pg_db

volumes:
  redis: 
    driver: local