### List movies
GET http://localhost:3000/movies

### Get a movie
GET http://localhost:3000/movies/bc14cdb1-42a8-4b4f-9f28-993ec1630eac

### Create a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "name":"Matrix",
    "genre":"Action",
    "director":"Peter Jackson",
    "year":1990
}

### Update a movie
PATCH http://localhost:3000/movies/3ecfee4f-de11-4f05-a1df-64f670fc943f
Content-Type: application/json

{
    "year":2000
}

### Delete a movie
DELETE http://localhost:3000/movies/3ecfee4f-de11-4f05-a1df-64f670fc943f

