### List movies
GET http://localhost:3000/movies

### Get a movie
GET http://localhost:3000/movies/1

### Create a movie
POST http://localhost:3000/movies

### Update a movie
PATCH http://localhost:3000/movies/1

### Delete a movie
DELETE http://localhost:3000/movies/1

