### List movies
GET http://localhost:3000/movies

### Get a movie
GET http://localhost:3000/movies/ddd10376-3440-4677-a7e5-8368f163c778

### Create a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "name":"Matrix",
    "genre":"Action",
    "director":"Peter Jackson",
    "year":1990
}

### Update a movie
PATCH http://localhost:3000/movies/ddd10376-3440-4677-a7e5-8368f163c778
Content-Type: application/json

{
    "year":2000
}

### Delete a movie
DELETE http://localhost:3000/movies/ddd10376-3440-4677-a7e5-8368f163c778

